// Generated by CoffeeScript 1.8.0
(function() {
  window.ColorsWidget = (function() {
    return {
      init: function(idElement, colors) {
        var list, resultTemp;
        list = '<ul class="bColor"><% _.forEach(colors, function(color) { %><li style="background:<%- color %>"></li><% }); %></ul>';
        resultTemp = _.template(list, {
          'colors': colors
        });
        return $(idElement).append(resultTemp);
      }
    };
  })();

}).call(this);
